# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Auto_Check_Log.ui'
#
# Created: Tue Feb 14 02:25:24 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Auto_Check_Log(object):
    def setupUi(self, Auto_Check_Log):
        Auto_Check_Log.setObjectName(_fromUtf8("Auto_Check_Log"))
        Auto_Check_Log.resize(1102, 712)
        font = QtGui.QFont()
        font.setPointSize(11)
        Auto_Check_Log.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("C:/E/电脑文件图标/可爱/86337.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Auto_Check_Log.setWindowIcon(icon)
        self.layoutWidget = QtGui.QWidget(Auto_Check_Log)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1081, 691))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.Lcom = QtGui.QLabel(self.layoutWidget)
        self.Lcom.setMinimumSize(QtCore.QSize(24, 15))
        self.Lcom.setMaximumSize(QtCore.QSize(24, 15))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Lcom.setFont(font)
        self.Lcom.setObjectName(_fromUtf8("Lcom"))
        self.horizontalLayout.addWidget(self.Lcom)
        self.cBcom = QtGui.QComboBox(self.layoutWidget)
        self.cBcom.setMinimumSize(QtCore.QSize(67, 21))
        self.cBcom.setMaximumSize(QtCore.QSize(67, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cBcom.setFont(font)
        self.cBcom.setObjectName(_fromUtf8("cBcom"))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.cBcom.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cBcom)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.Lbaud = QtGui.QLabel(self.layoutWidget)
        self.Lbaud.setMinimumSize(QtCore.QSize(45, 15))
        self.Lbaud.setMaximumSize(QtCore.QSize(45, 15))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Lbaud.setFont(font)
        self.Lbaud.setObjectName(_fromUtf8("Lbaud"))
        self.horizontalLayout_2.addWidget(self.Lbaud)
        self.lEbaud = QtGui.QLineEdit(self.layoutWidget)
        self.lEbaud.setMinimumSize(QtCore.QSize(91, 21))
        self.lEbaud.setMaximumSize(QtCore.QSize(91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEbaud.setFont(font)
        self.lEbaud.setText(_fromUtf8(""))
        self.lEbaud.setObjectName(_fromUtf8("lEbaud"))
        self.horizontalLayout_2.addWidget(self.lEbaud)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.Ldevice_model = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Ldevice_model.setFont(font)
        self.Ldevice_model.setObjectName(_fromUtf8("Ldevice_model"))
        self.horizontalLayout_17.addWidget(self.Ldevice_model)
        self.lEdevice_model = QtGui.QLineEdit(self.layoutWidget)
        self.lEdevice_model.setMinimumSize(QtCore.QSize(61, 21))
        self.lEdevice_model.setMaximumSize(QtCore.QSize(61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEdevice_model.setFont(font)
        self.lEdevice_model.setText(_fromUtf8(""))
        self.lEdevice_model.setObjectName(_fromUtf8("lEdevice_model"))
        self.horizontalLayout_17.addWidget(self.lEdevice_model)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_17)
        spacerItem2 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.Lmac = QtGui.QLabel(self.layoutWidget)
        self.Lmac.setMinimumSize(QtCore.QSize(54, 15))
        self.Lmac.setMaximumSize(QtCore.QSize(54, 15))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Lmac.setFont(font)
        self.Lmac.setObjectName(_fromUtf8("Lmac"))
        self.horizontalLayout_4.addWidget(self.Lmac)
        self.lEmac = QtGui.QLineEdit(self.layoutWidget)
        self.lEmac.setMinimumSize(QtCore.QSize(61, 21))
        self.lEmac.setMaximumSize(QtCore.QSize(61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEmac.setFont(font)
        self.lEmac.setText(_fromUtf8(""))
        self.lEmac.setObjectName(_fromUtf8("lEmac"))
        self.horizontalLayout_4.addWidget(self.lEmac)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.Lonoff = QtGui.QLabel(self.layoutWidget)
        self.Lonoff.setMinimumSize(QtCore.QSize(60, 15))
        self.Lonoff.setMaximumSize(QtCore.QSize(60, 15))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Lonoff.setFont(font)
        self.Lonoff.setObjectName(_fromUtf8("Lonoff"))
        self.horizontalLayout_5.addWidget(self.Lonoff)
        self.ckBonoff = QtGui.QCheckBox(self.layoutWidget)
        self.ckBonoff.setMinimumSize(QtCore.QSize(53, 19))
        self.ckBonoff.setMaximumSize(QtCore.QSize(53, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ckBonoff.setFont(font)
        self.ckBonoff.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ckBonoff.setObjectName(_fromUtf8("ckBonoff"))
        self.horizontalLayout_5.addWidget(self.ckBonoff)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        spacerItem4 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.pBbegin = QtGui.QPushButton(self.layoutWidget)
        self.pBbegin.setMinimumSize(QtCore.QSize(75, 23))
        self.pBbegin.setMaximumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pBbegin.setFont(font)
        self.pBbegin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pBbegin.setObjectName(_fromUtf8("pBbegin"))
        self.horizontalLayout_6.addWidget(self.pBbegin)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.Lfile_name = QtGui.QLabel(self.layoutWidget)
        self.Lfile_name.setMinimumSize(QtCore.QSize(90, 15))
        self.Lfile_name.setMaximumSize(QtCore.QSize(90, 15))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Lfile_name.setFont(font)
        self.Lfile_name.setObjectName(_fromUtf8("Lfile_name"))
        self.horizontalLayout_3.addWidget(self.Lfile_name)
        self.lEfile_name = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lEfile_name.sizePolicy().hasHeightForWidth())
        self.lEfile_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEfile_name.setFont(font)
        self.lEfile_name.setObjectName(_fromUtf8("lEfile_name"))
        self.horizontalLayout_3.addWidget(self.lEfile_name)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.Lfeedid = QtGui.QLabel(self.layoutWidget)
        self.Lfeedid.setMinimumSize(QtCore.QSize(54, 15))
        self.Lfeedid.setMaximumSize(QtCore.QSize(54, 15))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Lfeedid.setFont(font)
        self.Lfeedid.setObjectName(_fromUtf8("Lfeedid"))
        self.horizontalLayout_19.addWidget(self.Lfeedid)
        self.lEfeedid = QtGui.QLineEdit(self.layoutWidget)
        self.lEfeedid.setMinimumSize(QtCore.QSize(61, 21))
        self.lEfeedid.setMaximumSize(QtCore.QSize(300, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEfeedid.setFont(font)
        self.lEfeedid.setText(_fromUtf8(""))
        self.lEfeedid.setObjectName(_fromUtf8("lEfeedid"))
        self.horizontalLayout_19.addWidget(self.lEfeedid)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.Lmail = QtGui.QLabel(self.layoutWidget)
        self.Lmail.setMaximumSize(QtCore.QSize(54, 15))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Lmail.setFont(font)
        self.Lmail.setObjectName(_fromUtf8("Lmail"))
        self.horizontalLayout_20.addWidget(self.Lmail)
        self.lEmail = QtGui.QLineEdit(self.layoutWidget)
        self.lEmail.setMinimumSize(QtCore.QSize(200, 21))
        self.lEmail.setMaximumSize(QtCore.QSize(300, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEmail.setFont(font)
        self.lEmail.setText(_fromUtf8(""))
        self.lEmail.setObjectName(_fromUtf8("lEmail"))
        self.horizontalLayout_20.addWidget(self.lEmail)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_19)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label.setAcceptDrops(False)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.Chiga, QtCore.QLocale.Uganda))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_5.addWidget(self.label)
        self.tBserial_log = QtGui.QTextBrowser(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tBserial_log.setFont(font)
        self.tBserial_log.setObjectName(_fromUtf8("tBserial_log"))
        self.verticalLayout_5.addWidget(self.tBserial_log)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_4.addWidget(self.label_3)
        self.textBrowser = QtGui.QTextBrowser(self.layoutWidget)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.verticalLayout_4.addWidget(self.textBrowser)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.horizontalLayout_18.addLayout(self.verticalLayout_6)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(3)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.ckB_0 = QtGui.QCheckBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ckB_0.sizePolicy().hasHeightForWidth())
        self.ckB_0.setSizePolicy(sizePolicy)
        self.ckB_0.setMinimumSize(QtCore.QSize(13, 0))
        self.ckB_0.setMaximumSize(QtCore.QSize(13, 16777215))
        self.ckB_0.setText(_fromUtf8(""))
        self.ckB_0.setObjectName(_fromUtf8("ckB_0"))
        self.horizontalLayout_7.addWidget(self.ckB_0)
        self.lEcheck_flag_0 = QtGui.QLineEdit(self.layoutWidget)
        self.lEcheck_flag_0.setMinimumSize(QtCore.QSize(161, 21))
        self.lEcheck_flag_0.setMaximumSize(QtCore.QSize(161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEcheck_flag_0.setFont(font)
        self.lEcheck_flag_0.setText(_fromUtf8(""))
        self.lEcheck_flag_0.setObjectName(_fromUtf8("lEcheck_flag_0"))
        self.horizontalLayout_7.addWidget(self.lEcheck_flag_0)
        self.lEcheck_num_0 = QtGui.QLineEdit(self.layoutWidget)
        self.lEcheck_num_0.setMinimumSize(QtCore.QSize(71, 21))
        self.lEcheck_num_0.setMaximumSize(QtCore.QSize(71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEcheck_num_0.setFont(font)
        self.lEcheck_num_0.setText(_fromUtf8(""))
        self.lEcheck_num_0.setObjectName(_fromUtf8("lEcheck_num_0"))
        self.horizontalLayout_7.addWidget(self.lEcheck_num_0)
        self.pBcheck_reset_0 = QtGui.QPushButton(self.layoutWidget)
        self.pBcheck_reset_0.setMinimumSize(QtCore.QSize(75, 23))
        self.pBcheck_reset_0.setMaximumSize(QtCore.QSize(75, 23))
        self.pBcheck_reset_0.setObjectName(_fromUtf8("pBcheck_reset_0"))
        self.horizontalLayout_7.addWidget(self.pBcheck_reset_0)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.ckB_1 = QtGui.QCheckBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ckB_1.sizePolicy().hasHeightForWidth())
        self.ckB_1.setSizePolicy(sizePolicy)
        self.ckB_1.setMinimumSize(QtCore.QSize(13, 0))
        self.ckB_1.setMaximumSize(QtCore.QSize(13, 16777215))
        self.ckB_1.setText(_fromUtf8(""))
        self.ckB_1.setObjectName(_fromUtf8("ckB_1"))
        self.horizontalLayout_8.addWidget(self.ckB_1)
        self.lEcheck_flag_1 = QtGui.QLineEdit(self.layoutWidget)
        self.lEcheck_flag_1.setMinimumSize(QtCore.QSize(161, 21))
        self.lEcheck_flag_1.setMaximumSize(QtCore.QSize(161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEcheck_flag_1.setFont(font)
        self.lEcheck_flag_1.setText(_fromUtf8(""))
        self.lEcheck_flag_1.setObjectName(_fromUtf8("lEcheck_flag_1"))
        self.horizontalLayout_8.addWidget(self.lEcheck_flag_1)
        self.lEcheck_num_1 = QtGui.QLineEdit(self.layoutWidget)
        self.lEcheck_num_1.setMinimumSize(QtCore.QSize(71, 21))
        self.lEcheck_num_1.setMaximumSize(QtCore.QSize(71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEcheck_num_1.setFont(font)
        self.lEcheck_num_1.setText(_fromUtf8(""))
        self.lEcheck_num_1.setObjectName(_fromUtf8("lEcheck_num_1"))
        self.horizontalLayout_8.addWidget(self.lEcheck_num_1)
        self.pBcheck_reset_1 = QtGui.QPushButton(self.layoutWidget)
        self.pBcheck_reset_1.setMinimumSize(QtCore.QSize(75, 23))
        self.pBcheck_reset_1.setMaximumSize(QtCore.QSize(75, 23))
        self.pBcheck_reset_1.setObjectName(_fromUtf8("pBcheck_reset_1"))
        self.horizontalLayout_8.addWidget(self.pBcheck_reset_1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.ckB_2 = QtGui.QCheckBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ckB_2.sizePolicy().hasHeightForWidth())
        self.ckB_2.setSizePolicy(sizePolicy)
        self.ckB_2.setMinimumSize(QtCore.QSize(13, 0))
        self.ckB_2.setMaximumSize(QtCore.QSize(13, 16777215))
        self.ckB_2.setText(_fromUtf8(""))
        self.ckB_2.setObjectName(_fromUtf8("ckB_2"))
        self.horizontalLayout_9.addWidget(self.ckB_2)
        self.lEcheck_flag_2 = QtGui.QLineEdit(self.layoutWidget)
        self.lEcheck_flag_2.setMinimumSize(QtCore.QSize(161, 21))
        self.lEcheck_flag_2.setMaximumSize(QtCore.QSize(161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEcheck_flag_2.setFont(font)
        self.lEcheck_flag_2.setText(_fromUtf8(""))
        self.lEcheck_flag_2.setObjectName(_fromUtf8("lEcheck_flag_2"))
        self.horizontalLayout_9.addWidget(self.lEcheck_flag_2)
        self.lEcheck_num_2 = QtGui.QLineEdit(self.layoutWidget)
        self.lEcheck_num_2.setMinimumSize(QtCore.QSize(71, 21))
        self.lEcheck_num_2.setMaximumSize(QtCore.QSize(71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEcheck_num_2.setFont(font)
        self.lEcheck_num_2.setText(_fromUtf8(""))
        self.lEcheck_num_2.setObjectName(_fromUtf8("lEcheck_num_2"))
        self.horizontalLayout_9.addWidget(self.lEcheck_num_2)
        self.pBcheck_reset_2 = QtGui.QPushButton(self.layoutWidget)
        self.pBcheck_reset_2.setMinimumSize(QtCore.QSize(75, 23))
        self.pBcheck_reset_2.setMaximumSize(QtCore.QSize(75, 23))
        self.pBcheck_reset_2.setObjectName(_fromUtf8("pBcheck_reset_2"))
        self.horizontalLayout_9.addWidget(self.pBcheck_reset_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.ckB_3 = QtGui.QCheckBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ckB_3.sizePolicy().hasHeightForWidth())
        self.ckB_3.setSizePolicy(sizePolicy)
        self.ckB_3.setMinimumSize(QtCore.QSize(13, 0))
        self.ckB_3.setMaximumSize(QtCore.QSize(13, 16777215))
        self.ckB_3.setText(_fromUtf8(""))
        self.ckB_3.setObjectName(_fromUtf8("ckB_3"))
        self.horizontalLayout_10.addWidget(self.ckB_3)
        self.lEcheck_flag_3 = QtGui.QLineEdit(self.layoutWidget)
        self.lEcheck_flag_3.setMinimumSize(QtCore.QSize(161, 21))
        self.lEcheck_flag_3.setMaximumSize(QtCore.QSize(161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEcheck_flag_3.setFont(font)
        self.lEcheck_flag_3.setText(_fromUtf8(""))
        self.lEcheck_flag_3.setObjectName(_fromUtf8("lEcheck_flag_3"))
        self.horizontalLayout_10.addWidget(self.lEcheck_flag_3)
        self.lEcheck_num_3 = QtGui.QLineEdit(self.layoutWidget)
        self.lEcheck_num_3.setMinimumSize(QtCore.QSize(71, 21))
        self.lEcheck_num_3.setMaximumSize(QtCore.QSize(71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEcheck_num_3.setFont(font)
        self.lEcheck_num_3.setText(_fromUtf8(""))
        self.lEcheck_num_3.setObjectName(_fromUtf8("lEcheck_num_3"))
        self.horizontalLayout_10.addWidget(self.lEcheck_num_3)
        self.pBcheck_reset_3 = QtGui.QPushButton(self.layoutWidget)
        self.pBcheck_reset_3.setMinimumSize(QtCore.QSize(75, 23))
        self.pBcheck_reset_3.setMaximumSize(QtCore.QSize(75, 23))
        self.pBcheck_reset_3.setObjectName(_fromUtf8("pBcheck_reset_3"))
        self.horizontalLayout_10.addWidget(self.pBcheck_reset_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.ckB_4 = QtGui.QCheckBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ckB_4.sizePolicy().hasHeightForWidth())
        self.ckB_4.setSizePolicy(sizePolicy)
        self.ckB_4.setMinimumSize(QtCore.QSize(13, 0))
        self.ckB_4.setMaximumSize(QtCore.QSize(13, 16777215))
        self.ckB_4.setText(_fromUtf8(""))
        self.ckB_4.setObjectName(_fromUtf8("ckB_4"))
        self.horizontalLayout_11.addWidget(self.ckB_4)
        self.lEcheck_flag_4 = QtGui.QLineEdit(self.layoutWidget)
        self.lEcheck_flag_4.setMinimumSize(QtCore.QSize(161, 21))
        self.lEcheck_flag_4.setMaximumSize(QtCore.QSize(161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEcheck_flag_4.setFont(font)
        self.lEcheck_flag_4.setText(_fromUtf8(""))
        self.lEcheck_flag_4.setObjectName(_fromUtf8("lEcheck_flag_4"))
        self.horizontalLayout_11.addWidget(self.lEcheck_flag_4)
        self.lEcheck_num_4 = QtGui.QLineEdit(self.layoutWidget)
        self.lEcheck_num_4.setMinimumSize(QtCore.QSize(71, 21))
        self.lEcheck_num_4.setMaximumSize(QtCore.QSize(71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEcheck_num_4.setFont(font)
        self.lEcheck_num_4.setText(_fromUtf8(""))
        self.lEcheck_num_4.setObjectName(_fromUtf8("lEcheck_num_4"))
        self.horizontalLayout_11.addWidget(self.lEcheck_num_4)
        self.pBcheck_reset_4 = QtGui.QPushButton(self.layoutWidget)
        self.pBcheck_reset_4.setMinimumSize(QtCore.QSize(75, 23))
        self.pBcheck_reset_4.setMaximumSize(QtCore.QSize(75, 23))
        self.pBcheck_reset_4.setObjectName(_fromUtf8("pBcheck_reset_4"))
        self.horizontalLayout_11.addWidget(self.pBcheck_reset_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.ckB_5 = QtGui.QCheckBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ckB_5.sizePolicy().hasHeightForWidth())
        self.ckB_5.setSizePolicy(sizePolicy)
        self.ckB_5.setMinimumSize(QtCore.QSize(13, 0))
        self.ckB_5.setMaximumSize(QtCore.QSize(13, 16777215))
        self.ckB_5.setText(_fromUtf8(""))
        self.ckB_5.setObjectName(_fromUtf8("ckB_5"))
        self.horizontalLayout_12.addWidget(self.ckB_5)
        self.lEcheck_flag_5 = QtGui.QLineEdit(self.layoutWidget)
        self.lEcheck_flag_5.setMinimumSize(QtCore.QSize(161, 21))
        self.lEcheck_flag_5.setMaximumSize(QtCore.QSize(161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEcheck_flag_5.setFont(font)
        self.lEcheck_flag_5.setText(_fromUtf8(""))
        self.lEcheck_flag_5.setObjectName(_fromUtf8("lEcheck_flag_5"))
        self.horizontalLayout_12.addWidget(self.lEcheck_flag_5)
        self.lEcheck_num_5 = QtGui.QLineEdit(self.layoutWidget)
        self.lEcheck_num_5.setMinimumSize(QtCore.QSize(71, 21))
        self.lEcheck_num_5.setMaximumSize(QtCore.QSize(71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEcheck_num_5.setFont(font)
        self.lEcheck_num_5.setText(_fromUtf8(""))
        self.lEcheck_num_5.setObjectName(_fromUtf8("lEcheck_num_5"))
        self.horizontalLayout_12.addWidget(self.lEcheck_num_5)
        self.pBcheck_reset_5 = QtGui.QPushButton(self.layoutWidget)
        self.pBcheck_reset_5.setMinimumSize(QtCore.QSize(75, 23))
        self.pBcheck_reset_5.setMaximumSize(QtCore.QSize(75, 23))
        self.pBcheck_reset_5.setObjectName(_fromUtf8("pBcheck_reset_5"))
        self.horizontalLayout_12.addWidget(self.pBcheck_reset_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.ckB_6 = QtGui.QCheckBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ckB_6.sizePolicy().hasHeightForWidth())
        self.ckB_6.setSizePolicy(sizePolicy)
        self.ckB_6.setMinimumSize(QtCore.QSize(13, 0))
        self.ckB_6.setMaximumSize(QtCore.QSize(13, 16777215))
        self.ckB_6.setText(_fromUtf8(""))
        self.ckB_6.setObjectName(_fromUtf8("ckB_6"))
        self.horizontalLayout_13.addWidget(self.ckB_6)
        self.lEcheck_flag_6 = QtGui.QLineEdit(self.layoutWidget)
        self.lEcheck_flag_6.setMinimumSize(QtCore.QSize(161, 21))
        self.lEcheck_flag_6.setMaximumSize(QtCore.QSize(161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEcheck_flag_6.setFont(font)
        self.lEcheck_flag_6.setText(_fromUtf8(""))
        self.lEcheck_flag_6.setObjectName(_fromUtf8("lEcheck_flag_6"))
        self.horizontalLayout_13.addWidget(self.lEcheck_flag_6)
        self.lEcheck_num_6 = QtGui.QLineEdit(self.layoutWidget)
        self.lEcheck_num_6.setMinimumSize(QtCore.QSize(71, 21))
        self.lEcheck_num_6.setMaximumSize(QtCore.QSize(71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEcheck_num_6.setFont(font)
        self.lEcheck_num_6.setText(_fromUtf8(""))
        self.lEcheck_num_6.setObjectName(_fromUtf8("lEcheck_num_6"))
        self.horizontalLayout_13.addWidget(self.lEcheck_num_6)
        self.pBcheck_reset_6 = QtGui.QPushButton(self.layoutWidget)
        self.pBcheck_reset_6.setMinimumSize(QtCore.QSize(75, 23))
        self.pBcheck_reset_6.setMaximumSize(QtCore.QSize(75, 23))
        self.pBcheck_reset_6.setObjectName(_fromUtf8("pBcheck_reset_6"))
        self.horizontalLayout_13.addWidget(self.pBcheck_reset_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.ckB_7 = QtGui.QCheckBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ckB_7.sizePolicy().hasHeightForWidth())
        self.ckB_7.setSizePolicy(sizePolicy)
        self.ckB_7.setMinimumSize(QtCore.QSize(13, 0))
        self.ckB_7.setMaximumSize(QtCore.QSize(13, 16777215))
        self.ckB_7.setText(_fromUtf8(""))
        self.ckB_7.setObjectName(_fromUtf8("ckB_7"))
        self.horizontalLayout_14.addWidget(self.ckB_7)
        self.lEcheck_flag_7 = QtGui.QLineEdit(self.layoutWidget)
        self.lEcheck_flag_7.setMinimumSize(QtCore.QSize(161, 21))
        self.lEcheck_flag_7.setMaximumSize(QtCore.QSize(161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEcheck_flag_7.setFont(font)
        self.lEcheck_flag_7.setText(_fromUtf8(""))
        self.lEcheck_flag_7.setObjectName(_fromUtf8("lEcheck_flag_7"))
        self.horizontalLayout_14.addWidget(self.lEcheck_flag_7)
        self.lEcheck_num_7 = QtGui.QLineEdit(self.layoutWidget)
        self.lEcheck_num_7.setMinimumSize(QtCore.QSize(71, 21))
        self.lEcheck_num_7.setMaximumSize(QtCore.QSize(71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEcheck_num_7.setFont(font)
        self.lEcheck_num_7.setText(_fromUtf8(""))
        self.lEcheck_num_7.setObjectName(_fromUtf8("lEcheck_num_7"))
        self.horizontalLayout_14.addWidget(self.lEcheck_num_7)
        self.pBcheck_reset_7 = QtGui.QPushButton(self.layoutWidget)
        self.pBcheck_reset_7.setMinimumSize(QtCore.QSize(75, 23))
        self.pBcheck_reset_7.setMaximumSize(QtCore.QSize(75, 23))
        self.pBcheck_reset_7.setObjectName(_fromUtf8("pBcheck_reset_7"))
        self.horizontalLayout_14.addWidget(self.pBcheck_reset_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.ckB_8 = QtGui.QCheckBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ckB_8.sizePolicy().hasHeightForWidth())
        self.ckB_8.setSizePolicy(sizePolicy)
        self.ckB_8.setMinimumSize(QtCore.QSize(13, 0))
        self.ckB_8.setMaximumSize(QtCore.QSize(13, 16777215))
        self.ckB_8.setText(_fromUtf8(""))
        self.ckB_8.setObjectName(_fromUtf8("ckB_8"))
        self.horizontalLayout_15.addWidget(self.ckB_8)
        self.lEcheck_flag_8 = QtGui.QLineEdit(self.layoutWidget)
        self.lEcheck_flag_8.setMinimumSize(QtCore.QSize(161, 21))
        self.lEcheck_flag_8.setMaximumSize(QtCore.QSize(161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEcheck_flag_8.setFont(font)
        self.lEcheck_flag_8.setText(_fromUtf8(""))
        self.lEcheck_flag_8.setObjectName(_fromUtf8("lEcheck_flag_8"))
        self.horizontalLayout_15.addWidget(self.lEcheck_flag_8)
        self.lEcheck_num_8 = QtGui.QLineEdit(self.layoutWidget)
        self.lEcheck_num_8.setMinimumSize(QtCore.QSize(71, 21))
        self.lEcheck_num_8.setMaximumSize(QtCore.QSize(71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEcheck_num_8.setFont(font)
        self.lEcheck_num_8.setText(_fromUtf8(""))
        self.lEcheck_num_8.setObjectName(_fromUtf8("lEcheck_num_8"))
        self.horizontalLayout_15.addWidget(self.lEcheck_num_8)
        self.pBcheck_reset_8 = QtGui.QPushButton(self.layoutWidget)
        self.pBcheck_reset_8.setMinimumSize(QtCore.QSize(75, 23))
        self.pBcheck_reset_8.setMaximumSize(QtCore.QSize(75, 23))
        self.pBcheck_reset_8.setObjectName(_fromUtf8("pBcheck_reset_8"))
        self.horizontalLayout_15.addWidget(self.pBcheck_reset_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.ckB_9 = QtGui.QCheckBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ckB_9.sizePolicy().hasHeightForWidth())
        self.ckB_9.setSizePolicy(sizePolicy)
        self.ckB_9.setMinimumSize(QtCore.QSize(13, 0))
        self.ckB_9.setMaximumSize(QtCore.QSize(13, 16777215))
        self.ckB_9.setText(_fromUtf8(""))
        self.ckB_9.setObjectName(_fromUtf8("ckB_9"))
        self.horizontalLayout_16.addWidget(self.ckB_9)
        self.lEcheck_flag_9 = QtGui.QLineEdit(self.layoutWidget)
        self.lEcheck_flag_9.setMinimumSize(QtCore.QSize(161, 21))
        self.lEcheck_flag_9.setMaximumSize(QtCore.QSize(161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEcheck_flag_9.setFont(font)
        self.lEcheck_flag_9.setText(_fromUtf8(""))
        self.lEcheck_flag_9.setObjectName(_fromUtf8("lEcheck_flag_9"))
        self.horizontalLayout_16.addWidget(self.lEcheck_flag_9)
        self.lEcheck_num_9 = QtGui.QLineEdit(self.layoutWidget)
        self.lEcheck_num_9.setMinimumSize(QtCore.QSize(71, 21))
        self.lEcheck_num_9.setMaximumSize(QtCore.QSize(71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEcheck_num_9.setFont(font)
        self.lEcheck_num_9.setText(_fromUtf8(""))
        self.lEcheck_num_9.setObjectName(_fromUtf8("lEcheck_num_9"))
        self.horizontalLayout_16.addWidget(self.lEcheck_num_9)
        self.pBcheck_reset_9 = QtGui.QPushButton(self.layoutWidget)
        self.pBcheck_reset_9.setMinimumSize(QtCore.QSize(75, 23))
        self.pBcheck_reset_9.setMaximumSize(QtCore.QSize(75, 23))
        self.pBcheck_reset_9.setObjectName(_fromUtf8("pBcheck_reset_9"))
        self.horizontalLayout_16.addWidget(self.pBcheck_reset_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_18.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.Lcom.setBuddy(self.cBcom)
        self.Lbaud.setBuddy(self.lEbaud)
        self.Ldevice_model.setBuddy(self.lEdevice_model)
        self.Lmac.setBuddy(self.lEmac)
        self.Lonoff.setBuddy(self.ckBonoff)
        self.Lfile_name.setBuddy(self.lEfile_name)
        self.Lfeedid.setBuddy(self.lEmac)
        self.Lmail.setBuddy(self.lEmac)
        self.label.setBuddy(self.tBserial_log)
        self.label_3.setBuddy(self.textBrowser)

        self.retranslateUi(Auto_Check_Log)
        QtCore.QObject.connect(self.pBbegin, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), Auto_Check_Log.script_start)
        QtCore.QObject.connect(self.pBcheck_reset_0, QtCore.SIGNAL(_fromUtf8("clicked()")), Auto_Check_Log.clear_num_0)
        QtCore.QObject.connect(self.pBcheck_reset_1, QtCore.SIGNAL(_fromUtf8("clicked()")), Auto_Check_Log.clear_num_1)
        QtCore.QObject.connect(self.pBcheck_reset_2, QtCore.SIGNAL(_fromUtf8("clicked()")), Auto_Check_Log.clear_num_2)
        QtCore.QObject.connect(self.pBcheck_reset_3, QtCore.SIGNAL(_fromUtf8("clicked()")), Auto_Check_Log.clear_num_3)
        QtCore.QObject.connect(self.pBcheck_reset_4, QtCore.SIGNAL(_fromUtf8("clicked()")), Auto_Check_Log.clear_num_4)
        QtCore.QObject.connect(self.pBcheck_reset_5, QtCore.SIGNAL(_fromUtf8("clicked()")), Auto_Check_Log.clear_num_5)
        QtCore.QObject.connect(self.pBcheck_reset_6, QtCore.SIGNAL(_fromUtf8("clicked()")), Auto_Check_Log.clear_num_6)
        QtCore.QObject.connect(self.pBcheck_reset_7, QtCore.SIGNAL(_fromUtf8("clicked()")), Auto_Check_Log.clear_num_7)
        QtCore.QObject.connect(self.pBcheck_reset_8, QtCore.SIGNAL(_fromUtf8("clicked()")), Auto_Check_Log.clear_num_8)
        QtCore.QObject.connect(self.pBcheck_reset_9, QtCore.SIGNAL(_fromUtf8("clicked()")), Auto_Check_Log.clear_num_9)
        QtCore.QObject.connect(self.tBserial_log, QtCore.SIGNAL(_fromUtf8("textChanged()")), Auto_Check_Log.record_data)
        QtCore.QObject.connect(self.lEcheck_flag_0, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Auto_Check_Log.text_change_0)
        QtCore.QObject.connect(self.lEcheck_flag_1, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Auto_Check_Log.text_change_1)
        QtCore.QObject.connect(self.lEcheck_flag_2, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Auto_Check_Log.text_change_2)
        QtCore.QObject.connect(self.lEcheck_flag_3, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Auto_Check_Log.text_change_3)
        QtCore.QObject.connect(self.lEcheck_flag_4, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Auto_Check_Log.text_change_4)
        QtCore.QObject.connect(self.lEcheck_flag_5, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Auto_Check_Log.text_change_5)
        QtCore.QObject.connect(self.lEcheck_flag_6, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Auto_Check_Log.text_change_6)
        QtCore.QObject.connect(self.lEcheck_flag_7, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Auto_Check_Log.text_change_7)
        QtCore.QObject.connect(self.lEcheck_flag_8, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Auto_Check_Log.text_change_8)
        QtCore.QObject.connect(self.lEcheck_flag_9, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Auto_Check_Log.text_change_9)
        QtCore.QObject.connect(self.lEdevice_model, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Auto_Check_Log.text_change_model)
        QtCore.QObject.connect(self.lEmac, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Auto_Check_Log.text_change_mac)
        QtCore.QObject.connect(self.lEbaud, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Auto_Check_Log.text_change_baud)
        QtCore.QObject.connect(self.ckBonoff, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), Auto_Check_Log.check_on_off)
        QtCore.QObject.connect(self.ckB_0, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), Auto_Check_Log.focus_log_0)
        QtCore.QObject.connect(self.ckB_1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), Auto_Check_Log.focus_log_1)
        QtCore.QObject.connect(self.ckB_2, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), Auto_Check_Log.focus_log_2)
        QtCore.QObject.connect(self.ckB_3, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), Auto_Check_Log.focus_log_3)
        QtCore.QObject.connect(self.ckB_4, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), Auto_Check_Log.focus_log_4)
        QtCore.QObject.connect(self.ckB_5, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), Auto_Check_Log.focus_log_5)
        QtCore.QObject.connect(self.ckB_6, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), Auto_Check_Log.focus_log_6)
        QtCore.QObject.connect(self.ckB_7, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), Auto_Check_Log.focus_log_7)
        QtCore.QObject.connect(self.ckB_8, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), Auto_Check_Log.focus_log_8)
        QtCore.QObject.connect(self.ckB_9, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), Auto_Check_Log.focus_log_9)
        QtCore.QObject.connect(self.textBrowser, QtCore.SIGNAL(_fromUtf8("textChanged()")), Auto_Check_Log.record_log)
        QtCore.QObject.connect(self.lEmail, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Auto_Check_Log.text_change_mail)
        QtCore.QMetaObject.connectSlotsByName(Auto_Check_Log)
        Auto_Check_Log.setTabOrder(self.cBcom, self.lEbaud)
        Auto_Check_Log.setTabOrder(self.lEbaud, self.lEmac)
        Auto_Check_Log.setTabOrder(self.lEmac, self.ckBonoff)
        Auto_Check_Log.setTabOrder(self.ckBonoff, self.pBbegin)
        Auto_Check_Log.setTabOrder(self.pBbegin, self.lEfile_name)
        Auto_Check_Log.setTabOrder(self.lEfile_name, self.tBserial_log)
        Auto_Check_Log.setTabOrder(self.tBserial_log, self.textBrowser)

    def retranslateUi(self, Auto_Check_Log):
        Auto_Check_Log.setWindowTitle(_translate("Auto_Check_Log", "log自动检查工具", None))
        self.Lcom.setText(_translate("Auto_Check_Log", "COM", None))
        self.cBcom.setItemText(0, _translate("Auto_Check_Log", "COM1", None))
        self.cBcom.setItemText(1, _translate("Auto_Check_Log", "COM2", None))
        self.cBcom.setItemText(2, _translate("Auto_Check_Log", "COM3", None))
        self.cBcom.setItemText(3, _translate("Auto_Check_Log", "COM4", None))
        self.cBcom.setItemText(4, _translate("Auto_Check_Log", "COM5", None))
        self.cBcom.setItemText(5, _translate("Auto_Check_Log", "COM6", None))
        self.cBcom.setItemText(6, _translate("Auto_Check_Log", "COM7", None))
        self.cBcom.setItemText(7, _translate("Auto_Check_Log", "COM8", None))
        self.cBcom.setItemText(8, _translate("Auto_Check_Log", "COM9", None))
        self.cBcom.setItemText(9, _translate("Auto_Check_Log", "COM10", None))
        self.cBcom.setItemText(10, _translate("Auto_Check_Log", "COM11", None))
        self.cBcom.setItemText(11, _translate("Auto_Check_Log", "COM12", None))
        self.cBcom.setItemText(12, _translate("Auto_Check_Log", "COM13", None))
        self.cBcom.setItemText(13, _translate("Auto_Check_Log", "COM14", None))
        self.cBcom.setItemText(14, _translate("Auto_Check_Log", "COM15", None))
        self.cBcom.setItemText(15, _translate("Auto_Check_Log", "COM16", None))
        self.cBcom.setItemText(16, _translate("Auto_Check_Log", "COM17", None))
        self.cBcom.setItemText(17, _translate("Auto_Check_Log", "COM18", None))
        self.cBcom.setItemText(18, _translate("Auto_Check_Log", "COM19", None))
        self.cBcom.setItemText(19, _translate("Auto_Check_Log", "COM20", None))
        self.cBcom.setItemText(20, _translate("Auto_Check_Log", "COM21", None))
        self.cBcom.setItemText(21, _translate("Auto_Check_Log", "COM22", None))
        self.cBcom.setItemText(22, _translate("Auto_Check_Log", "COM23", None))
        self.cBcom.setItemText(23, _translate("Auto_Check_Log", "COM24", None))
        self.cBcom.setItemText(24, _translate("Auto_Check_Log", "COM25", None))
        self.cBcom.setItemText(25, _translate("Auto_Check_Log", "COM26", None))
        self.cBcom.setItemText(26, _translate("Auto_Check_Log", "COM27", None))
        self.cBcom.setItemText(27, _translate("Auto_Check_Log", "COM28", None))
        self.cBcom.setItemText(28, _translate("Auto_Check_Log", "COM29", None))
        self.cBcom.setItemText(29, _translate("Auto_Check_Log", "COM30", None))
        self.cBcom.setItemText(30, _translate("Auto_Check_Log", "COM31", None))
        self.cBcom.setItemText(31, _translate("Auto_Check_Log", "COM32", None))
        self.cBcom.setItemText(32, _translate("Auto_Check_Log", "COM33", None))
        self.cBcom.setItemText(33, _translate("Auto_Check_Log", "COM34", None))
        self.cBcom.setItemText(34, _translate("Auto_Check_Log", "COM35", None))
        self.cBcom.setItemText(35, _translate("Auto_Check_Log", "COM36", None))
        self.cBcom.setItemText(36, _translate("Auto_Check_Log", "COM37", None))
        self.cBcom.setItemText(37, _translate("Auto_Check_Log", "COM38", None))
        self.cBcom.setItemText(38, _translate("Auto_Check_Log", "COM39", None))
        self.cBcom.setItemText(39, _translate("Auto_Check_Log", "COM40", None))
        self.cBcom.setItemText(40, _translate("Auto_Check_Log", "COM41", None))
        self.cBcom.setItemText(41, _translate("Auto_Check_Log", "COM42", None))
        self.cBcom.setItemText(42, _translate("Auto_Check_Log", "COM43", None))
        self.cBcom.setItemText(43, _translate("Auto_Check_Log", "COM44", None))
        self.cBcom.setItemText(44, _translate("Auto_Check_Log", "COM45", None))
        self.cBcom.setItemText(45, _translate("Auto_Check_Log", "COM46", None))
        self.cBcom.setItemText(46, _translate("Auto_Check_Log", "COM47", None))
        self.cBcom.setItemText(47, _translate("Auto_Check_Log", "COM48", None))
        self.cBcom.setItemText(48, _translate("Auto_Check_Log", "COM49", None))
        self.cBcom.setItemText(49, _translate("Auto_Check_Log", "COM50", None))
        self.Lbaud.setText(_translate("Auto_Check_Log", "波特率", None))
        self.Ldevice_model.setText(_translate("Auto_Check_Log", "设备型号", None))
        self.Lmac.setText(_translate("Auto_Check_Log", "Mac地址", None))
        self.Lonoff.setText(_translate("Auto_Check_Log", "在线状况", None))
        self.ckBonoff.setText(_translate("Auto_Check_Log", "在线", None))
        self.pBbegin.setText(_translate("Auto_Check_Log", "开始", None))
        self.Lfile_name.setText(_translate("Auto_Check_Log", "文件命名方式", None))
        self.lEfile_name.setText(_translate("Auto_Check_Log", "GN-Model-ONline/OFFline-Mac-[%Y-%m-%d_%H-%M-%S].log", None))
        self.Lfeedid.setText(_translate("Auto_Check_Log", "Feedid", None))
        self.Lmail.setText(_translate("Auto_Check_Log", "邮箱", None))
        self.label.setText(_translate("Auto_Check_Log", "串口打印", None))
        self.label_3.setText(_translate("Auto_Check_Log", "运行日志", None))
        self.label_4.setText(_translate("Auto_Check_Log", "统计", None))
        self.pBcheck_reset_0.setText(_translate("Auto_Check_Log", "清零", None))
        self.pBcheck_reset_1.setText(_translate("Auto_Check_Log", "清零", None))
        self.pBcheck_reset_2.setText(_translate("Auto_Check_Log", "清零", None))
        self.pBcheck_reset_3.setText(_translate("Auto_Check_Log", "清零", None))
        self.pBcheck_reset_4.setText(_translate("Auto_Check_Log", "清零", None))
        self.pBcheck_reset_5.setText(_translate("Auto_Check_Log", "清零", None))
        self.pBcheck_reset_6.setText(_translate("Auto_Check_Log", "清零", None))
        self.pBcheck_reset_7.setText(_translate("Auto_Check_Log", "清零", None))
        self.pBcheck_reset_8.setText(_translate("Auto_Check_Log", "清零", None))
        self.pBcheck_reset_9.setText(_translate("Auto_Check_Log", "清零", None))

